# -*- coding: utf-8 -*-
"""招標.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iznQrRbYsX-0SstE6bDS31EoFcmcsqbh
"""

from datetime import datetime, timedelta

# ---------------------------------------------------------
# 判斷今天是否為「本月最後一次的週一或週五」
# 邏輯：從今天開始往後找，直到月底為止，
#      如果找不到下一個「週一或週五」，代表今天就是本月最後一次寄信日
# ---------------------------------------------------------
def is_last_send_day_of_month(today: datetime = None) -> bool:
    if today is None:
        today = datetime.now()

    # 今天必須本身就是週一(0)或週五(4)，才需要判斷是否為「最後一次」
    if today.weekday() not in (0, 4):
        return False

    # 找出本月最後一天
    if today.month == 12:
        next_month_first_day = datetime(today.year + 1, 1, 1)
    else:
        next_month_first_day = datetime(today.year, today.month + 1, 1)
    last_day_of_month = next_month_first_day - timedelta(days=1)

    # 從明天開始檢查到月底為止，是否還有下一個週一或週五
    check_date = today + timedelta(days=1)
    while check_date <= last_day_of_month:
        if check_date.weekday() in (0, 4):
            return False  # 後面還有寄信日，今天不是最後一次
        check_date += timedelta(days=1)

    return True  # 後面都沒有寄信日了，今天就是本月最後一次
today = datetime.now()
is_month_last_send = is_last_send_day_of_month(today)

import requests
import time
import random
import json
import pandas as pd
from difflib import SequenceMatcher
import re
import contextlib
import io
import os
from datetime import datetime
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

BASE_URL = "https://pcc-api.openfun.app/api/searchbytitle"
START_PAGE = 1
END_PAGE = 8 if is_month_last_send else 2
DELAY_MIN = 2   # 最短延遲秒數
DELAY_MAX = 5   # 最長延遲秒數

# 要額外索取的詳細欄位（對應政府採購網原始公告的欄位路徑）
EXTRA_COLUMNS = [
    "採購資料:採購金額級距",
    "採購資料:採購金額級距",
    "url",
    "已公告資料:預算金額",
    "標案內容:預算金額",
    "採購資料:預算金額",
    "招標資料:是否屬統包",
    "決標資料:總決標金額",
    "標案內容:公開閱覽日期",
    "已公告資料:開標時間",
    "領投開標:開標時間"
]


def fetch_pages(query="鐵路"):
    all_records = []

    for page in range(START_PAGE, END_PAGE + 1):
        print(f"抓取第 {page} 頁...")
        try:
            # requests 會自動處理 columns[] 這種重複參數與 URL 編碼
            resp = requests.get(
                BASE_URL,
                params={
                    "query": query,
                    "page": page,
                    "columns[]": EXTRA_COLUMNS,
                },
                timeout=15,
            )
            resp.raise_for_status()
            data = resp.json()

            records = data.get("records", [])
            all_records.extend(records)
            print(f"  取得 {len(records)} 筆，累積 {len(all_records)} 筆")

            total_pages = data.get("total_pages", END_PAGE)
            if page >= total_pages:
                print("已達最後一頁，提前結束")
                break

        except requests.exceptions.HTTPError as e:
            if resp.status_code == 403:
                print("⚠️ 收到 403，可能被 Cloudflare 阻擋，建議稍後再試或聯繫網站方")
                break
            else:
                print(f"HTTP 錯誤: {e}")
                break
        except requests.exceptions.RequestException as e:
            print(f"請求失敗: {e}")
            break

        if page < END_PAGE:
            delay = random.uniform(DELAY_MIN, DELAY_MAX)
            print(f"  等待 {delay:.1f} 秒...")
            time.sleep(delay)

    return all_records


if __name__ == "__main__":
    queries = ["捷運", "鐵路", "高鐵", "運輸"]  # 這裡放你想搜尋的所有關鍵字

    all_records = []
    seen_ids = set()  # 用來去除重複的資料（依實際欄位調整，例如網址或標題）

    for q in queries:
        print(f"正在搜尋：{q} ...")
        results = fetch_pages(query=q)

        for r in results:
            # 假設每筆資料有唯一識別欄位，例如 r["url"] 或 r["id"]
            key = r.get("url") or r.get("id") or r.get("title")
            if key not in seen_ids:
                seen_ids.add(key)
                all_records.append(r)

    print(f"總共取得 {len(all_records)} 筆不重複資料")

    with open("搜尋結果_合併.json", "w", encoding="utf-8") as f:
        json.dump(all_records, f, ensure_ascii=False, indent=2)

    print(f"\n完成，共取得 {len(all_records)} 筆資料，已存至 搜尋結果_合併.json")

    # 印出第一筆看看 detail 欄位有沒有抓到值
    if all_records:
        print("\n--- 第一筆資料範例 ---")
        print(json.dumps(all_records[0], ensure_ascii=False, indent=2))

# ---------------------------------------------------------
# 從 companies.name_key 中，抓出「得標廠商」（排除「未得標廠商」）
# ---------------------------------------------------------
def extract_winning_companies(companies: dict) -> list:
    name_key = companies.get("name_key", {}) or {}
    winners = []
    for name, keys in name_key.items():
        for k in keys:
            # 「得標廠商」出現在 key 裡，但要排除「未得標廠商」的情況
            if "得標廠商" in k and "未得標廠商" not in k:
                winners.append(name)
                break  # 該廠商只要有任一 key 符合就算得標，不重複加入
    return winners

import re

CJK_PATTERN = re.compile(r'[\u4e00-\u9fff]')

def is_english_only(name: str) -> bool:
    """判斷名稱是否為純英文（不含任何中文字）。"""
    return bool(name) and not CJK_PATTERN.search(name)


# ---------------------------------------------------------
# 過濾 companies dict：
# - 純英文名稱的廠商，原則上刪除
# - 除非：(a) 該筆記錄所有廠商都只有英文名 -> 全部保留
#        (b) 該廠商是得標廠商 -> 保留
# 同步更新 names / ids / name_key / id_key
# ---------------------------------------------------------
def filter_companies_dict(companies: dict, winning_names: set) -> dict:
    if not companies:
        return companies

    old_names = companies.get("names", []) or []
    old_ids = companies.get("ids", []) or []
    name_key = companies.get("name_key", {}) or {}
    id_key = companies.get("id_key", {}) or {}

    if not old_names:
        return companies

    all_english_only = all(is_english_only(n) for n in old_names)

    def should_keep(n: str) -> bool:
        if not is_english_only(n):
            return True                # 含中文，一律保留
        if all_english_only:
            return True                # 全部都只有英文名，全部保留
        if n in winning_names:
            return True                # 得標廠商，即使純英文也保留
        return False                   # 其餘純英文名稱刪除

    keep_names_set = {n for n in old_names if should_keep(n)}

    new_names = [n for n in old_names if n in keep_names_set]
    new_name_key = {n: keys for n, keys in name_key.items() if n in keep_names_set}

    # ids / id_key 依「name_key 對照到的名稱是否保留」同步過濾
    # 建立 id -> 是否保留 的判斷（透過 id_key 找出該 id 對應哪些 key，
    # 再反查該 id 在 name_key 中對應的名稱是否被保留）
    # 因為原始資料沒有直接 id<->name 對照表，這裡改用「保留下來的 name_key」
    # 反查其 keys 是否與 id_key 有交集來判斷
    kept_keys = set()
    for keys in new_name_key.values():
        kept_keys.update(keys)

    new_id_key = {}
    for cid, keys in id_key.items():
        overlapped = [k for k in keys if k in kept_keys]
        if overlapped:
            new_id_key[cid] = keys

    new_ids = [cid for cid in old_ids if cid in new_id_key]

    new_companies = dict(companies)
    new_companies["names"] = new_names
    new_companies["ids"] = new_ids
    new_companies["name_key"] = new_name_key
    new_companies["id_key"] = new_id_key
    return new_companies

# ---------------------------------------------------------
# 1. 用剛剛抓到的 all_records 建立 DataFrame（不用重新讀檔）
# ---------------------------------------------------------
def flatten_record(rec):
    brief = rec.get("brief", {})
    raw_companies = brief.get("companies", {})
    detail = rec.get("detail", {}) or {}

    # 先用「原始未過濾」的 companies 算出得標廠商名單
    winning_companies = extract_winning_companies(raw_companies)
    winning_set = set(winning_companies)

    # 再依規則過濾 companies（純英文名刪除，除非全英文或得標廠商）
    companies = filter_companies_dict(raw_companies, winning_set)

    return {
        "date": rec.get("date"),
        "filename": rec.get("filename"),
        "type": brief.get("type"),
        "title": brief.get("title"),
        "category": brief.get("category"),
        "company_names": "、".join(companies.get("names", [])),
        "得標廠商": "、".join(winning_companies),  # 得標名單不受過濾影響，維持完整
        "job_number": rec.get("job_number"),
        "unit_id": rec.get("unit_id"),
        "unit_name": rec.get("unit_name"),
        "採購金額級距": detail.get("採購資料:採購金額級距") or detail.get("已公告資料:採購金額級距"),
        "預算金額": detail.get("採購資料:預算金額") or detail.get("已公告資料:預算金額") or detail.get("標案內容:預算金額"),
        "是否屬統包": detail.get("招標資料:是否屬統包"),
        "總決標金額": detail.get("決標資料:總決標金額"),
        "公開閱覽日期": detail.get("標案內容:公開閱覽日期"),
        "開標時間": detail.get("已公告資料:開標時間") or detail.get("領投開標:開標時間"),
        "pcc_url": detail.get("url"),
        "tender_api_url": rec.get("tender_api_url"),
    }

df = pd.DataFrame([flatten_record(rec) for rec in all_records])
df["date"] = pd.to_datetime(df["date"].astype(str), format="%Y%m%d")
df = df.sort_values("date", ascending=False).reset_index(drop=True)

# ---------------------------------------------------------
# 清理金額欄位：去除逗號「,」與後綴「元」，轉成 int
# 若原始值為空/NaN/無法轉換，則保留為 pd.NA（欄位型別用 Int64 可容納空值）
# ---------------------------------------------------------
def clean_amount(x):
    if pd.isna(x):
        return pd.NA
    s = str(x).strip()
    s = s.replace(",", "")      # 去除千分位逗號，否則 int() 會噴 ValueError
    s = s.replace("元", "")     # 去除後綴「元」
    s = s.strip()
    if s == "":
        return pd.NA
    try:
        return int(s)
    except ValueError:
        return pd.NA  # 遇到無法解析的格式（例如夾雜其他文字），先設為缺值

df["預算金額"] = df["預算金額"].apply(clean_amount).astype("Int64")
df["總決標金額"] = df["總決標金額"].apply(clean_amount).astype("Int64")

print(f"全部資料：{len(df)} 筆")
print(df["採購金額級距"].value_counts(dropna=False))  # 先看實際有哪些級距值


# ---------------------------------------------------------
# 2. 用 pandas 篩選「查核金額以上未達巨額」和「巨額」
#    並考慮：如果一個案件被歸類為「巨額」或「查核金額以上未達巨額」，
#    則該案件的所有相關紀錄（無論其本身的採購金額級距欄位有無值）都應該被納入。
# ---------------------------------------------------------
target_levels = ["查核金額以上未達巨額", "巨額"]

# 先找出所有屬於目標金額級距的案件編號（unit_id, job_number）
# 這一步篩選會排除那些沒有採購金額級距的紀錄，但在下一步會被補回
target_cases_df = df[df["採購金額級距"].isin(target_levels)]
target_case_ids = target_cases_df[["unit_id", "job_number"]].drop_duplicates()

# 然後，從原始 df 中，選取所有屬於這些案件編號的紀錄
df_filtered = df.merge(target_case_ids, on=["unit_id", "job_number"], how="inner")
df_filtered = df_filtered.sort_values("date", ascending=False).reset_index(drop=True)

print(f"\n篩選後：{len(df_filtered)} 筆")
df_filtered

# ---------------------------------------------------------
# 0. 前提：df_filtered 已經是「巨額 / 查核金額以上未達巨額」篩選後的結果
#    欄位至少包含：date, type, title, unit_id, job_number, unit_name, pcc_url, 採購金額級距
# ---------------------------------------------------------

# ---------------------------------------------------------
# 1. 定義四個階段的分類規則
#    用「關鍵字」比對 type 字串，而不是完全比對，
#    這樣不管是「更正公告」還是「經公開評選...更正公告」都能歸到同一階段
#    注意：「無法決標」必須排在「決標」判斷之前，
#    否則「無法決標」裡也含有「決標」兩字，會被誤判成決標階段
# ---------------------------------------------------------
def classify_stage(type_str: str) -> str:
    if type_str is None:
        return "其他"
    if "無法決標" in type_str:
        return "無法決標"
    if "閱覽"  in type_str:
        return "公開閱覽"
    if "更正決標" in type_str:
        return "決標"
    if "決標" in type_str:
        return "決標"
    if "更正" in type_str or "更新" in type_str:
        return "更正"
    if "招標" in type_str or "取得報價" in type_str or "徵求" in type_str:
        return "招標"
    return "其他"


df_filtered["stage"] = df_filtered["type"].apply(classify_stage)


# ---------------------------------------------------------
# 2. 依 (unit_id, job_number, stage) 分組，
#    把同一階段裡多筆公告的「日期＋公告類型」整併成 list（依時間排序）
# ---------------------------------------------------------
def summarize_group(g: pd.DataFrame) -> pd.Series:
    g_sorted = g.sort_values("date")
    entries = [
        f"{d.strftime('%Y-%m-%d')}｜{t}"
        for d, t in zip(g_sorted["date"], g_sorted["type"])
    ]
    return pd.Series({
        "entries": entries,          # 該階段所有公告的時間＋類型清單
        "latest_date": g_sorted["date"].iloc[-1],
        "latest_url": g_sorted["pcc_url"].iloc[-1],  # 只留時間最新那筆的 url
    })

stage_summary = (
    df_filtered
    .groupby(["unit_id", "job_number", "stage"])
    .apply(summarize_group)
    .reset_index()
)


# ---------------------------------------------------------
# 3. 把「招標 / 更正 / 決標 / 無法決標」四階段從長格式轉成寬格式（每案一列，四欄，只留紀錄 list）
# ---------------------------------------------------------
def build_stage_dict(g: pd.DataFrame) -> pd.Series:
    result = {}
    for stage in ["公開閱覽", "招標", "更正", "決標", "無法決標"]:
        row = g[g["stage"] == stage]
        result[f"{stage}_紀錄"] = None if len(row) == 0 else row.iloc[0]["entries"]
    return pd.Series(result)

case_wide = (
    stage_summary
    .groupby(["unit_id", "job_number"])
    .apply(build_stage_dict)
    .reset_index()
)


# ---------------------------------------------------------
# 4. 計算整案「單一最新 url」，以及取每案「最後一筆非空值」的預算金額／是否屬統包／總決標金額
#    （不分階段，因為這些欄位可能分散在不同階段才會出現）
# ---------------------------------------------------------
def last_non_null(s: pd.Series):
    s = s.dropna()
    return s.iloc[-1] if len(s) > 0 else None

def build_case_extra(g: pd.DataFrame) -> pd.Series:
    g_sorted = g.sort_values("date")
    return pd.Series({
        "最新url": g_sorted["pcc_url"].dropna().iloc[-1] if g_sorted["pcc_url"].notna().any() else None,
        "預算金額": last_non_null(g_sorted["預算金額"]) if "預算金額" in g_sorted else None,
        "是否屬統包": last_non_null(g_sorted["是否屬統包"]) if "是否屬統包" in g_sorted else None,
        "總決標金額": last_non_null(g_sorted["總決標金額"]) if "總決標金額" in g_sorted else None,
    })

case_extra = (
    df_filtered
    .groupby(["unit_id", "job_number"])
    .apply(build_case_extra)
    .reset_index()
)


# ---------------------------------------------------------
# 5. 補回案件的基本資訊（標題、機關名稱、金額級距），合併所有欄位並整理順序
# ---------------------------------------------------------
case_info = (
    df_filtered
    .drop_duplicates(subset=["unit_id", "job_number"])
    [["unit_id", "job_number", "title", "unit_name", "採購金額級距", "category", "得標廠商","公開閱覽日期","開標時間"]]
)

result_df = (
    case_info
    .merge(case_wide, on=["unit_id", "job_number"])
    .merge(case_extra, on=["unit_id", "job_number"])
)

result_df = result_df[[
    "title", "unit_name", "採購金額級距", "公開閱覽_紀錄",
    "招標_紀錄", "更正_紀錄", "決標_紀錄", "無法決標_紀錄",
    "得標廠商", "預算金額", "是否屬統包", "總決標金額",
    "最新url","公開閱覽日期","開標時間",
    "unit_id", "job_number", "category"
]]

print(f"整併後共 {len(result_df)} 案")
result_df

unique_values = result_df['unit_name'].unique()
print(unique_values)
result_df.to_excel('result.xlsx', index=False)
from google.colab import files
files.download('result.xlsx')

import pandas as pd
import re
from difflib import SequenceMatcher

import re

# ---------------------------------------------------------
# 找出字串中「括號／引號包住的區段」（含括號本身），回傳遮罩
# 涵蓋：() （） 「」 "" ''
# 目的：像「或」引出的替代名稱通常會用括號/引號包起來，
# 這類區段整段（含括號）都要移除，避免影響最長共同前綴比對
# ---------------------------------------------------------
def get_bracket_removal_mask(s: str) -> list:
    mask = [False] * len(s)
    patterns = [
        r'\([^)]*\)',   # ( ... )
        r'（[^）]*）',   # （ ... ）
        r'「[^」]*」',   # 「 ... 」
        r'"[^"]*"',     # " ... "
        r"'[^']*'",     # ' ... '
    ]
    for pat in patterns:
        for m in re.finditer(pat, s):
            for i in range(m.start(), m.end()):
                mask[i] = True
    return mask

def strip(s: str) -> str:
    # 0. 先整段移除括號/引號包住的內容（含括號本身），
    #    例如替代名稱「A(或稱B)」中的「(或稱B)」整段刪除
    bracket_mask = get_bracket_removal_mask(s)
    s = ''.join(ch for i, ch in enumerate(s) if not bracket_mask[i])

    # 先擷取開頭連續的英文/數字（保留不動）
    m = re.match(r'^[A-Za-z0-9]+', s)
    prefix = m.group(0) if m else ""
    rest = s[len(prefix):]

    # 對剩餘部分做原本的清理邏輯
    rest = re.sub(r'[A-Za-z0-9]+', '', rest)          # 去除英文、數字（規則2：開頭已保留，其餘不論前後段一律去除）
    rest = re.sub(r'[()（）\-－_/、\s]+', '', rest)     # 去除常見符號、空白
    rest = re.sub(r'」', '', rest)
    rest = re.sub(r'「', '', rest)
    rest = re.sub(r'[\'"]', '', rest)                  # 去除殘留單引號/雙引號

    result = prefix + rest
    return result



def strip_with_map(s: str):
    bracket_mask = get_bracket_removal_mask(s)  # 標記要整段跳過（不列入清理後字串）的位置

    m = re.match(r'^[A-Za-z0-9]+', s)
    prefix_len = len(m.group(0)) if m else 0

    cleaned_chars = []
    orig_indices = []

    # 開頭英數字整段保留（即使開頭剛好落在括號遮罩內也優先保留，符合規則2「開頭的不用去除」）
    for i in range(prefix_len):
        cleaned_chars.append(s[i])
        orig_indices.append(i)

    # 其餘部分逐字判斷是否要清除
    i = prefix_len
    remove_symbols = set('()（）-－_/、')
    while i < len(s):
        ch = s[i]
        if bracket_mask[i]:
            # 屬於括號/引號整段區間，直接跳過（規則1）
            i += 1
            continue
        if re.match(r'[A-Za-z0-9]', ch):
            i += 1
            continue
        if ch in remove_symbols or ch.isspace():
            i += 1
            continue
        if ch in '「」':
            i += 1
            continue
        if ch in '\'"':
            i += 1
            continue
        cleaned_chars.append(ch)
        orig_indices.append(i)
        i += 1

    return ''.join(cleaned_chars), orig_indices

# ---------------------------------------------------------
# Helper functions for Longest Common PREFIX（只能從首字元開始比對）
# ---------------------------------------------------------
def get_longest_common_prefix_pairwise(a: str, b: str) -> str:
    """找出兩個字串「從第一個字元開始」相同的最長前綴。"""
    if not a or not b:
        return ""
    max_len = min(len(a), len(b))
    i = 0
    while i < max_len and a[i] == b[i]:
        i += 1
    return a[:i]

# ---------------------------------------------------------
# 找出一群標題「以清理後文字判斷相同長度」，
# 但輸出使用『完整原文』（含被清除的符號/英數字）的共同前綴
# ---------------------------------------------------------
def find_full_text_common_title(titles: list) -> str:
    if not titles:
        return ""

    cleaned_list, map_list, orig_list = [], [], []
    for t in titles:
        c, m = strip_with_map(t)
        if c:
            cleaned_list.append(c)
            map_list.append(m)
            orig_list.append(t)

    if not cleaned_list:
        return ""
    if len(cleaned_list) == 1:
        return orig_list[0]  # 只有一筆時，直接回傳完整原文

    lcs_so_far = get_longest_common_prefix_pairwise(cleaned_list[0], cleaned_list[1])
    for i in range(2, len(cleaned_list)):
        if not lcs_so_far:
            break
        lcs_so_far = get_longest_common_prefix_pairwise(lcs_so_far, cleaned_list[i])

    L = len(lcs_so_far)
    if L == 0:
        return ""

    # 用第一筆的原文，取到「清理後第 L 個字元」對應的原文位置，
    # 藉此還原成完整文字（含中間被清掉的符號、英數字）
    end_idx = map_list[0][L - 1] + 1
    return orig_list[0][:end_idx]

# ---------------------------------------------------------
# 1. 相似度分組
# ---------------------------------------------------------
def longest_common_prefix_len(a: str, b: str) -> int:
    """回傳兩字串從首字元開始相同的長度。"""
    if not a or not b:
        return 0
    max_len = min(len(a), len(b))
    i = 0
    while i < max_len and a[i] == b[i]:
        i += 1
    return i


def group_by_similar_title(titles: list, min_common_len: int = 9) -> list:
    n = len(titles)
    parent = list(range(n))
    cleaned_titles = [strip(t) for t in titles]   # 這裡已經包含去除「和」

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(x, y):
        rx, ry = find(x), find(y)
        if rx != ry:
            parent[rx] = ry

    for i in range(n):
        for j in range(i + 1, n):
            if longest_common_prefix_len(cleaned_titles[i], cleaned_titles[j]) >= min_common_len:
                union(i, j)

    roots = [find(i) for i in range(n)]
    unique_roots = {r: idx for idx, r in enumerate(sorted(set(roots)))}
    return [unique_roots[r] for r in roots]


# ---------------------------------------------------------
# 2. 上層彙總表：一個「相似組別」＝一個大計畫
# ---------------------------------------------------------
def build_summary_table(df: pd.DataFrame, group_col: str = "相似組別") -> pd.DataFrame:
    money_cols = [c for c in ["預算金額", "總決標金額"] if c in df.columns]

    rows = []
    for group_id, g in df.groupby(group_col):
        g = g.sort_values("date")
        type_counts = g["type"].value_counts()

        # 同一組別底下所有細項中的最大金額（跨 預算金額 / 總決標金額 取最大）
        if money_cols:
            max_amt = pd.to_numeric(
                g[money_cols].stack(), errors="coerce"
            ).max()
        else:
            max_amt = None

        row = {
            "相似組別": group_id,
            "案件數": len(g),
            "涵蓋標題": find_full_text_common_title(g["title"].unique().tolist()),  # 完整原文版共同標題
            "所屬機關": " ／ ".join(g["unit_name"].dropna().unique()),
            "招標次數": int(type_counts.get("招標", 0)),
            "更正次數": int(type_counts.get("更正", 0)),
            "決標次數": int(type_counts.get("決標", 0)),
            "最早日期": g["date"].min(),
            "最新日期": g["date"].max(),
            "代表決標金額": last_non_null(g.loc[g["type"] == "決標", "總決標金額"]) if "總決標金額" in g.columns else None,
            "最大金額": max_amt,  # 用來排序的依據
            "最新url": g["pcc_url"].dropna().iloc[-1] if g["pcc_url"].notna().any() else None,
        }
        rows.append(row)

    result = (
        pd.DataFrame(rows)
        .sort_values("最大金額", ascending=False, na_position="last")
        .reset_index(drop=True)
    )
    ordered_cols = [
        "相似組別", "案件數", "涵蓋標題", "所屬機關",
        "招標次數", "更正次數", "決標次數",
        "最早日期", "最新日期", "代表決標金額", "最大金額", "最新url",
    ]
    return result[[c for c in ordered_cols if c in result.columns]]


def last_non_null(s: pd.Series):
    s = s.dropna()
    return s.iloc[-1] if len(s) > 0 else None


# ---------------------------------------------------------
# 3. 下層明細表：每一筆招標／更正／決標各自一列，各自的日期＋金額
# ---------------------------------------------------------
def build_detail_table(df: pd.DataFrame, group_col: str = "相似組別") -> pd.DataFrame:
    money_cols = [c for c in ["預算金額", "總決標金額"] if c in df.columns]
    base_cols = [
        group_col, "date", "type", "title", "unit_name", "category",
        "company_names", "得標廠商", "開標時間", "公開閱覽日期", "pcc_url",
    ]
    cols = base_cols + money_cols

    df_detail = (
        df[[c for c in cols if c in df.columns]]
        .sort_values([group_col, "date"])
        .reset_index(drop=True)
    )
    return df_detail


# ---------------------------------------------------------
# 4. 主流程：加上分組欄位後，分別產生上層＋下層兩張表
# ---------------------------------------------------------
def build_grouped_tables(df: pd.DataFrame, title_col: str = "title", min_common_len: int = 9):
    df = df.copy()
    df["相似組別"] = group_by_similar_title(df[title_col].fillna("").tolist(), min_common_len)

    df_summary = build_summary_table(df)
    df_detail = build_detail_table(df)
    return df_summary, df_detail


# ---------------------------------------------------------
# 5. 階層式印出：大計畫 → 分項標題 → 每筆招標/更正/決標紀錄
# ---------------------------------------------------------
def print_nested(df_summary: pd.DataFrame, df_detail: pd.DataFrame):
    money_cols = [c for c in ["預算金額", "總決標金額", "採購金額級距"] if c in df_detail.columns]

    for _, s in df_summary.iterrows():
        # 直接使用涵蓋標題，因為它現在已經是最長共同連續字串
        print(f"\n■ {s['涵蓋標題']}")

        gid = s["相似組別"] # Define gid here
        sub = df_detail[df_detail["相似組別"] == gid]

        # 再依「標題」分組，得到每個分項標案
        for title, g_title in sub.groupby("title", sort=False):
            g_title = g_title.sort_values("date")
            print(f"  -「{title}」")
            for _, d in g_title.iterrows():
                amt_parts = []
                for c in money_cols:
                    if pd.notna(d[c]):
                        amt_parts.append(f"{c}={d[c]}")
                amt_str = "，".join(amt_parts) if amt_parts else "無金額資訊"
                print(f"    - {d['date'].strftime('%Y-%m-%d')}｜{d['type']}｜{amt_str}")

# ---------------------------------------------------------
# 使用方式
# ---------------------------------------------------------
pd.set_option("display.max_colwidth", None)
df_summary, df_detail = build_grouped_tables(df_filtered, min_common_len=6)

#df_detail  # 每筆招標/更正/決標的下層明細表
print_nested(df_summary, df_detail)  # 想直接用階層方式印出來看的話用這個
df_summary   # 大計畫上層彙總表

# ---------------------------------------------------------
# 金額轉換：滿千逗號分隔的英文表示法（含「元」）
# ---------------------------------------------------------
def format_amount_en(n) -> str:
    if pd.isna(n):
        return ""
    n = int(n)
    return f"{n:,}元"


# ---------------------------------------------------------
# 金額轉換：中文表示法，遇兆／億／萬才寫出（含「元」）
# 例如 1,234,000,000 -> 12億3400萬元
# ---------------------------------------------------------
def format_amount_zh(n) -> str:
    if pd.isna(n):
        return ""
    n = int(n)
    if n == 0:
        return "0元"

    parts = []
    remainder = n
    units = [("兆", 10**12), ("億", 10**8), ("萬", 10**4)]
    for name, val in units:
        if remainder >= val:
            count = remainder // val
            parts.append(f"{count}{name}")
            remainder %= val
    if remainder > 0:
        parts.append(str(remainder))

    return "".join(parts) + "元"

def get_nested_html(df_summary: pd.DataFrame, df_detail: pd.DataFrame) -> str:
    money_cols = [c for c in ["預算金額", "總決標金額", "採購金額級距"] if c in df_detail.columns]
    html_out = []

    for _, s in df_summary.iterrows():
        gid = s["相似組別"]
        main_title = s['涵蓋標題'].split(' ／ ')[0]

        # 大計畫外框
        html_out.append(f'''
        <div style="margin-top: 16px; border: 1px solid #cbd5e0; border-radius: 8px; overflow: hidden; background: #fff;">
          <div style="background-color: #2b6cb0; color: white; padding: 10px 12px; font-weight: bold; font-size: 15px;">
            📦 {main_title}
          </div>
          <div style="padding: 12px;">
        ''')

        sub = df_detail[df_detail["相似組別"] == gid]

        for title, g_title in sub.groupby("title", sort=False):
            g_title = g_title.sort_values("date")

            # 小計畫底下的「所屬機關」與「得標廠商」：取該小計畫所有列的不重複值並串接
            unit_names = " ／ ".join(
                sorted(set(u for u in g_title.get("unit_name", pd.Series(dtype=str)).dropna() if u))
            )


            # 所有相關廠商（沿用 company_names）
            all_companies = []
            for cn in g_title.get("company_names", pd.Series(dtype=str)).dropna():
                if cn:
                    all_companies.extend([c for c in cn.split("、") if c])
            all_companies = sorted(set(all_companies))

            # 得標廠商名單（用來判斷哪些要加粗）
            winning_set = set()
            for wn in g_title.get("得標廠商", pd.Series(dtype=str)).dropna():
                if wn:
                    winning_set.update(c for c in wn.split("、") if c)

            # 得標廠商加粗，其餘維持一般字重
            company_display_parts = [
                f"<b>{c}</b>" if c in winning_set else c
                for c in all_companies
            ]
            company_names = "、".join(company_display_parts)

            html_out.append(f'''
            <div style="margin-bottom: 12px; border-left: 3px solid #4299e1; padding-left: 8px;">
              <div style="font-weight: bold; color: #2d3748; font-size: 14px;">📌 {title}</div>
              {f'<div style="font-size: 12px; color: #718096; margin-top: 2px;">🏢 {unit_names}</div>' if unit_names else ''}
              {f'<div style="font-size: 12px; color: #718096; margin-top: 2px;">🏆 {company_names}</div>' if company_names else ''}
            ''')

            for _, d in g_title.iterrows():
                amt_parts = []
                for c in money_cols:
                    val = d[c]
                    if pd.isna(val):
                        continue
                    if c in ("預算金額", "總決標金額"):
                        en_str = format_amount_en(val)
                        zh_str = format_amount_zh(val)
                        amt_parts.append(f"{c}: {en_str}（{zh_str}）")
                    else:
                        amt_parts.append(f"{c}: {val}")

                amt_str = " | ".join(amt_parts) if amt_parts else "無金額資訊"

                raw_date = d.get('date', '')
                if pd.notna(raw_date):
                    date_str = pd.to_datetime(raw_date).strftime('%Y-%m-%d')
                else:
                    date_str = "無日期"

                pcc_url = d.get('pcc_url', '')
                has_url = pd.notna(pcc_url) and str(pcc_url).strip() != ''

                stage_type = d.get('type', '')

                stage_style_list = [
                    ("無法決標", {"bg": "#fff5f5", "color": "#c53030", "border": "#feb2b2"}),
                    ("決標",     {"bg": "#f0fff4", "color": "#276749", "border": "#9ae6b4"}),
                    ("更正",     {"bg": "#fffff0", "color": "#975a16", "border": "#faf089"}),
                    ("公開閱覽", {"bg": "#ffffff", "color": "#1a202c", "border": "#cbd5e0"}),
                    ("招標",     {"bg": "#ebf8ff", "color": "#2b6cb0", "border": "#bee3f8"}),
                ]
                default_style = {"bg": "#edf2f7", "color": "#4a5568", "border": "#cbd5e0"}

                style = default_style
                for keyword, s_style in stage_style_list:
                    if keyword in stage_type:
                        style = s_style
                        break

                badge_inline_style = (
                    f'background-color: {style["bg"]}; color: {style["color"]}; '
                    f'border: 1px solid {style["border"]}; padding: 1px 6px; border-radius: 4px; '
                    f'font-size: 11px; font-weight: bold; margin-left: 8px;'
                )

                pcc_url = d.get('pcc_url', '')
                has_url = pd.notna(pcc_url) and str(pcc_url).strip() != ''

                if stage_type and has_url:
                    stage_badge = (
                        f'<a href="{pcc_url}" target="_blank" rel="noopener noreferrer" '
                        f'style="{badge_inline_style} text-decoration: none; display: inline-block;">'
                        f'{stage_type}</a>'
                    )
                elif stage_type:
                    stage_badge = f'<span style="{badge_inline_style}">{stage_type}</span>'
                else:
                    stage_badge = ''

                # 新增：招標階段顯示「開標時間」，公開閱覽階段顯示「公開閱覽日期」
                extra_date_str = ''
                if "招標" in stage_type:
                    open_time = d.get('開標時間', '')
                    if pd.notna(open_time) and str(open_time).strip() != '':
                        extra_date_str = f'<span style="margin-left: 8px; color: #4a5568;">開標時間：{open_time}</span>'
                elif "公開閱覽" in stage_type:
                    review_date = d.get('公開閱覽日期', '')
                    if pd.notna(review_date) and str(review_date).strip() != '':
                        extra_date_str = f'<span style="margin-left: 8px; color: #4a5568;">公開閱覽日期：{review_date}</span>'
                html_out.append(f'''
                <div style="font-size: 12px; color: #4a5568; margin-top: 6px; background: #f7fafc; padding: 8px; border-radius: 6px;">
                  <div style="display: flex; align-items: center;">📅 <b>{date_str}</b>{stage_badge}{extra_date_str}</div>
                  <div style="color: #2b6cb0; margin-top: 4px;">💰 {amt_str}</div>
                </div>
                ''')

            html_out.append('</div>')
        html_out.append('</div></div>')

    return "".join(html_out)

# ---------------------------------------------------------
# 產生「七天內公開閱覽 / 招標中」表格區塊
# 篩選規則：type 含「招標」或「公開閱覽」，且 date 落在過去 N 天內
# ---------------------------------------------------------
def build_upcoming_week_html(df_detail: pd.DataFrame, days: int = 7) -> str:
    cutoff = pd.Timestamp.now().normalize() - pd.Timedelta(days=days)

    mask_type = df_detail["type"].fillna("").apply(
        lambda t: ("招標" in t or "公開閱覽" in t) and "無法決標" not in t
    )
    mask_date = df_detail["date"] >= cutoff

    recent = df_detail[mask_type & mask_date].sort_values("date", ascending=False)

    if recent.empty:
        return '''
        <div style="margin-top: 16px; padding: 12px; background: #f7fafc; border-radius: 8px; color: #718096; font-size: 13px;">
          過去 7 天內沒有新增的公開閱覽或招標中案件。
        </div>
        '''

    # 與 get_nested_html 共用的階段配色
    stage_style_list = [
        ("無法決標", {"bg": "#fff5f5", "color": "#c53030", "border": "#feb2b2"}),
        ("決標",     {"bg": "#f0fff4", "color": "#276749", "border": "#9ae6b4"}),
        ("更正",     {"bg": "#fffff0", "color": "#975a16", "border": "#faf089"}),
        ("公開閱覽", {"bg": "#ffffff", "color": "#1a202c", "border": "#cbd5e0"}),
        ("招標",     {"bg": "#ebf8ff", "color": "#2b6cb0", "border": "#bee3f8"}),
    ]
    default_style = {"bg": "#edf2f7", "color": "#4a5568", "border": "#cbd5e0"}

    def get_style(stage_type: str):
        for keyword, s_style in stage_style_list:
            if keyword in stage_type:
                return s_style
        return default_style

    cell_style = (
        "font-size:13px; font-family:'Microsoft JhengHei','PingFang TC',Arial,sans-serif; "
        "line-height:1.4; word-break: break-word; overflow-wrap: break-word;"
    )

    rows_html = []
    for _, d in recent.iterrows():
        stage_type = d.get('type', '') or ''
        style = get_style(stage_type)
        badge_inline_style = (
            f'background-color: {style["bg"]}; color: {style["color"]}; '
            f'border: 1px solid {style["border"]}; padding: 2px 8px; border-radius: 4px; '
            f'font-size: 11px; font-weight: bold; display: inline-block; '
            f'word-break: break-word; white-space: normal;'
        )

        pcc_url = d.get('pcc_url', '')
        has_url = pd.notna(pcc_url) and str(pcc_url).strip() != ''
        link_html = (
            f'<a href="{pcc_url}" target="_blank" rel="noopener noreferrer" '
            f'style="color: #2b6cb0; text-decoration: none; font-weight: bold;">查看公告</a>'
            if has_url else '-'
        )

        # 招標顯示「{時間} 開標」、公開閱覽顯示「{時間} 公開閱覽」
        if "招標" in stage_type:
            key_date = d.get('開標時間', '')
            key_date_suffix = "開標"
        elif "公開閱覽" in stage_type:
            key_date = d.get('公開閱覽日期', '')
            key_date_suffix = "公開閱覽"
        else:
            key_date = ''
            key_date_suffix = ''

        if pd.notna(key_date) and str(key_date).strip() != '':
            key_date_str = f"{key_date} {key_date_suffix}"
        else:
            key_date_str = '-'

        raw_date = d.get('date', '')
        date_str = pd.to_datetime(raw_date).strftime('%Y-%m-%d') if pd.notna(raw_date) else '-'

        budget = d.get('預算金額', None)
        budget_str = format_amount_zh(budget) if pd.notna(budget) else '-'

        title = d.get('title', '') or '-'
        unit_name = d.get('unit_name', '') or '-'
        category = d.get('category', '') or '-'

        rows_html.append(f'''
        <tr>
          <td style="{cell_style} text-align:left;">{title}</td>
          <td style="{cell_style} text-align:left;">{unit_name}</td>
          <td style="{cell_style} text-align:center;">{category}</td>
          <td style="{cell_style} text-align:center;"><span style="{badge_inline_style}">{stage_type}</span></td>
          <td style="{cell_style} text-align:center;">{date_str}</td>
          <td style="{cell_style} text-align:center;">{key_date_str}</td>
          <td style="{cell_style} text-align:center;">{budget_str}</td>
          <td style="{cell_style} text-align:center;">{link_html}</td>
        </tr>
        ''')

    table_html = f'''
    <div style="margin-top: 16px; border: 1px solid #cbd5e0; border-radius: 8px; overflow: hidden; background: #fff;">
      <div style="background-color: #1a365d; color: white; padding: 10px 12px; font-weight: bold; font-size: 15px;">
        過去 {days} 天內：公開閱覽 / 招標中案件（共 {len(recent)} 筆）
      </div>
      <div style="padding: 12px; overflow-x: auto;">
        <table style="width:100%; table-layout: fixed; border-collapse: collapse; font-family: 'Microsoft JhengHei','PingFang TC',Arial,sans-serif; font-size:13px; color:#333;">
          <thead>
            <tr>
              <th style="width: 24%; background:#1a365d; color:#fff; padding:8px; border:1px solid #1a365d;">標案名稱</th>
              <th style="width: 14%; background:#1a365d; color:#fff; padding:8px; border:1px solid #1a365d;">機關名稱</th>
              <th style="width: 10%; background:#1a365d; color:#fff; padding:8px; border:1px solid #1a365d;">標的分類</th>
              <th style="width: 8%; background:#1a365d; color:#fff; padding:8px; border:1px solid #1a365d;">階段</th>
              <th style="width: 10%; background:#1a365d; color:#fff; padding:8px; border:1px solid #1a365d;">公告日期</th>
              <th style="width: 14%; background:#1a365d; color:#fff; padding:8px; border:1px solid #1a365d;">關鍵時間</th>
              <th style="width: 12%; background:#1a365d; color:#fff; padding:8px; border:1px solid #1a365d;">預算金額</th>
              <th style="width: 8%; background:#1a365d; color:#fff; padding:8px; border:1px solid #1a365d;">連結</th>
            </tr>
          </thead>
          <tbody>
            {''.join(rows_html)}
          </tbody>
        </table>
      </div>
    </div>
    '''
    return table_html

# ---------------------------------------------------------
# 控制區塊：判斷今天是否要附上「專案階層明細」名片式清單
# ---------------------------------------------------------
today = datetime.now()
is_month_last_send = is_last_send_day_of_month(today)

data_time_str = today.strftime("%Y-%m-%d %H:%M")
upcoming_html = build_upcoming_week_html(df_detail, days=7)

# 只有月底最後一次寄信日才產生明細清單，否則留空字串
if is_month_last_send:
    nested_card_html = get_nested_html(df_summary, df_detail)
    nested_card_html = f'''
    <h4 style="color: #2d3748; margin-top: 24px; margin-bottom: 8px;">專案階層明細：</h4>
    {nested_card_html}
    '''
else:
    nested_card_html = '本次無提供'

print(f"今天：{today.strftime('%Y-%m-%d')}（週{'一二三四五六日'[today.weekday()]}）")
print(f"是否為本月最後一次寄信日：{is_month_last_send}")

# 假設資料時間，實際使用時可替換成你的時間變數，例如：datetime.now().strftime("%Y-%m-%d %H:%M")
data_time_str = datetime.now().strftime("%Y-%m-%d %H:%M")
upcoming_html = build_upcoming_week_html(df_detail, days=7)


# 3. 組合完整的 HTML
full_email_html = f"""
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container">
    <!-- 1. 信件主標題 -->
    <h3 style="color: #1a365d; margin-top: 0; margin-bottom: 12px;">採購公告查詢結果通知</h3>

    <!-- 2. 信件基本招呼語與說明 -->
    <p style="color: #4a5568; font-size: 14px; margin-bottom: 16px;">
      您好：<br>
      以下為最新系統自動彙整之採購公告與專案明細，供您參考與參閱。
    </p>

    <!-- 3. 資料時間說明（建議用提示框顯眼呈現） -->
      <strong>資料擷取時間：</strong>{data_time_str}
    </div>

    <!-- 4. 七天內公開閱覽／招標中資料表 -->
    {upcoming_html}

    <!-- 5. 階層式手機卡片 -->
    <h4 style="color: #2d3748; margin-top: 24px; margin-bottom: 8px;">專案階層明細：</h4>
    {nested_card_html}

    <!-- 6. 信件頁尾補充資訊 -->
    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 30px 0 15px 0;">
    <p style="color: #a0aec0; font-size: 12px; line-height: 1.5; margin: 0;">
      ※ 本信件由系統自動發送，請勿直接回覆。<br>
      ※ 如對查詢結果有疑問，請洽系統管理員或相關業務承辦人員。
    </p>
  </div>
</body>
</html>
"""

from google.colab import files

# 1. 將 full_email_html 寫入 local 檔案
filename = "email_template.html"
with open(filename, "w", encoding="utf-8") as f:
  f.write(full_email_html)

# 2. 觸發瀏覽器下載
files.download(filename)

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

import os

sender_email = os.environ.get("EMAIL_ADDRESS")
sender_password = os.environ.get("EMAIL_PASSWORD")

server = smtplib.SMTP('smtp.gmail.com', 587)
server.starttls()
server.login(sender_email, sender_password)



message = MIMEMultipart("alternative")
message["Subject"] = "採購資料查詢結果"
message["From"] = sender
message["To"] = receiver


# 3. 附加 HTML 內容
part = MIMEText(full_email_html, "html")
message.attach(part)

# 4. 發送郵件 (以 Gmail SMTP 為例)
try:
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, receiver, message.as_string())
    print("信件已成功寄出！")
except Exception as e:
    print(f"寄信失敗: {e}")

